name: "📦 Build Server Package"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gatherFacts:
    runs-on: ubuntu-22.04
    outputs:
      appRepo: ${{ steps.variables.outputs.APP_REPO }}
      appGitSha: ${{ steps.variables.outputs.APP_GIT_SHA }}
      appVersion: ${{ steps.variables.outputs.APP_VERSION }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Gather Variables"
        id: variables
        run: |-
          set -exu

          echo "APP_REPO=$(yq --exit-status '.repository' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}
          echo "APP_GIT_SHA=$(yq --exit-status '.git_sha' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}
          echo "APP_VERSION=$(yq --exit-status '.version' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}

  debian:
    uses: ./.github/workflows/_meta-debBuild.yaml
    needs:
      - gatherFacts
    strategy:
      matrix:
        TARGET_ARCH:
          - amd64
          - arm64
          - armhf
    with:
      buildOs: debian
      buildImageTag: debian-20221120
      debSpec: server
      cpuArch: ${{ matrix.TARGET_ARCH }}
      repository: ${{ needs.gatherFacts.outputs.appRepo }}
      repositoryRef: ${{ needs.gatherFacts.outputs.appGitSha }}


  ubuntu:
    uses: ./.github/workflows/_meta-debBuild.yaml
    needs:
      - gatherFacts
    strategy:
      matrix:
        TARGET_ARCH:
          - amd64
          - arm64
          - armhf
    with:
      buildOs: ubuntu
      buildImageTag: ubuntu-20221120
      debSpec: server
      cpuArch: ${{ matrix.TARGET_ARCH }}
      repository: ${{ needs.gatherFacts.outputs.appRepo }}
      repositoryRef: ${{ needs.gatherFacts.outputs.appGitSha }}

  publishDeb:
    needs:
      - gatherFacts
      - debian
      - ubuntu
    if: ${{ ! contains(needs.gatherFacts.outputs.appVersion, 'unstable') }}
    runs-on: ubuntu-22.04
    steps:
      - name: "Download Artifacts"
        uses: actions/download-artifact@v3

      - name: "Debug"
        run: ls -la
