name: "📦 Build Web-Client Package"

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  gatherFacts:
    runs-on: ubuntu-22.04
    outputs:
      appRepo: ${{ steps.variables.outputs.APP_REPO }}
      appGitSha: ${{ steps.variables.outputs.APP_GIT_SHA }}
      appVersion: ${{ steps.variables.outputs.APP_VERSION }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Gather Variables"
        id: variables
        run: |-
          set -exu

          echo "APP_REPO=$(yq --exit-status '.repository' web-client/metaValues.yaml)" >> ${GITHUB_OUTPUT}
          echo "APP_GIT_SHA=$(yq --exit-status '.git_sha' web-client/metaValues.yaml)" >> ${GITHUB_OUTPUT}
          echo "APP_VERSION=$(yq --exit-status '.version' web-client/metaValues.yaml)" >> ${GITHUB_OUTPUT}

  debian:
    uses: ./.github/workflows/_meta-debBuild.yaml
    with:
      buildOs: debian
      buildImageTag: debian-20221120
      debSpec: web-client
      cpuArch: all
      repository: ${{ needs.gatherFacts.outputs.appRepo }}
      repositoryRef: ${{ needs.gatherFacts.outputs.appGitSha }}


  ubuntu:
    uses: ./.github/workflows/_meta-debBuild.yaml
    with:
      buildOs: ubuntu
      buildImageTag: ubuntu-20221120
      debSpec: web-client
      cpuArch: all
      repository: ${{ needs.gatherFacts.outputs.appRepo }}
      repositoryRef: ${{ needs.gatherFacts.outputs.appGitSha }}

  publishDeb:
    needs:
      - gatherFacts
      - buildDeb
    if: ${{ ! contains(needs.gatherFacts.outputs.appVersion, 'unstable') }}
    runs-on: ubuntu-22.04
    steps:
      - name: "Download Artifacts"
        uses: actions/download-artifact@v3

      - name: "Debug"
        run: ls -la
